services:
  axon:
    image: axoniq/axonserver:2024.1.2-jdk-17-nonroot
    ports:
      - '8024:8024'
      - '8124:8124'
    environment:
      "axoniq.axonserver.standalone": "true"
  neo4j:
    image: neo4j
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/verysecret
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=verysecret
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=verysecret
      - ME_CONFIG_MONGODB_SERVER=mongodb

