server:
  port: ${SERVER_PORT:3000}
  max-http-request-header-size: 5MB
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true


spring:
  application:
    name: crag-db
  neo4j:
    uri: ${NEO4J_URL:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:verysecret}
  liquibase:
    enabled: true
    change-log: classpath:changeLog.yaml
axon:
  axonserver:
    servers: ${AXON_SERVERS:localhost}
  serializer:
    general: jackson
    events: jackson
    messages: jackson

#  eventhandling:
#    processors:
#      crag-processor:
#        mode: tracking
#        source: crag-source
