apiVersion: v1
kind: Service
metadata:
  name: neo4jdb
  namespace: crag-db
  labels:
    app: neo4jdb
spec:
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app: neo4jdb
  type: ClusterIP