---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  namespace: crag-db
  labels:
    app: axonserver
spec:
  ports:
    - name: gui
      port: 8024
      targetPort: 8024
  selector:
    app: axonserver
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  namespace: crag-db
  labels:
    app: axonserver
spec:
  ports:
    - name: grpc
      port: 8124
      targetPort: 8124
  selector:
    app: axonserver
  type: ClusterIP