apiVersion: apps/v1
kind: Deployment
metadata:
  name: crag-db
  namespace: crag-db
  labels:
    app: crag-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crag-db
  template:
    metadata:
      labels:
        app: crag-db
    spec:
#      serviceAccountName: crag-db-sa
      containers:
        - name: crag-db
          image: crag-db
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9000
              name: management
          envFrom:
            - configMapRef:
                name: crag-db-config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1111
            capabilities:
              drop:
                - ALL