apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: crag-db
  labels:
    app: namespace-reader
  name: crag-db-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-read-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-rolebinding
subjects:
  - kind: ServiceAccount
    namespace: crag-db
    name: crag-db-sa
roleRef:
  kind: ClusterRole
  name: cluster-read-role
  apiGroup: rbac.authorization.k8s.io